spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    username: test
    password: test
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
    exchange: test_exchange
    company:
      queue: company_queque
    messageVisit:
      queue: message_visit_queque

server:
  port: 8091
