spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    username: test
    password: test
    exchange: test_exchange
    company:
      queue: company_queque
    messageVisit:
      queue: message_visit_queque

server:
  port: 8090